pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Kobeyvines/alx-backend-python.git',
                    credentialsId: 'github-creds_id'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m pip install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    pytest messaging_app/tests --junitxml=messaging_app/test-results/results.xml || true
                '''
            }
        }
    }

    post {
        always {
            junit 'messaging_app/test-results/*.xml'
        }
    }
}
