apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
  labels:
    app: messaging-app
spec:
  type: ClusterIP
  selector:
    app: messaging-app   # NOTE: no "version" here, so both blue+green get traffic
  ports:
  - name: http
    port: 8000
    targetPort: 8000
