pipeline {
    agent any
    tools {
        jenkins.plugins.shiningpanda.tools.PythonInstallation 'python3'
    }
    stages {
        stage('Install Dependencies') {
            steps {
                sh '''
                    cd messaging_app
                    python3 -m pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }
        stage('Run Tests') {
            steps {
                sh '''
                    cd messaging_app
                    pytest --junitxml=test-results/results.xml || true
                '''
            }
        }
    }
    post {
        always {
            junit 'messaging_app/test-results/*.xml'
        }
    }
}
