pipeline {
    agent any
    tools {
        python 'Python3'   // matches the name you gave in Tools
    }
    stages {
        stage('Install Dependencies') {
            steps {
                sh '''
                cd messaging_app
                pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest pytest-cov
                '''
            }
        }
        stage('Run Tests') {
            steps {
                sh '''
                cd messaging_app
                pytest --junitxml=results.xml || true
                '''
            }
        }
    }
    post {
        always {
            junit 'messaging_app/results.xml'
            archiveArtifacts artifacts: 'messaging_app/results.xml', fingerprint: true
        }
    }
}
