pipeline {
    agent any

    tools {
        python 'Python3'
    }

    environment {
        PIP_CACHE_DIR = '.pip-cache'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Kobeyvines/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                cd messaging_app
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                cd messaging_app
                pytest --junitxml=results.xml
                '''
            }
        }
    }

    post {
        always {
            junit 'messaging_app/results.xml'
            archiveArtifacts artifacts: 'messaging_app/results.xml', fingerprint: true
        }
    }
}
